---
name: aapdashboard
services:
  db:
    image: registry.redhat.io/rhel8/postgresql-15:latest
    env_file:
      - path: "./.env"
        required: true
    environment:
      # - POSTGRESQL_ADMIN_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_USER=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
       - type: volume
         source: postgres-data
         target: /var/lib/psql/data
       - type: bind
         source: ./compose/init-db.sh
         target: /usr/share/container-scripts/postgresql/start/10-grant-createdb.sh
         read_only: true
         bind:
           create_host_path: false

  redis:
    image: registry.redhat.io/rhel8/redis-6:latest
    user: "1001:0"
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ./compose/redis.conf
        target: /etc/redis.conf
        read_only: true
        bind:
          create_host_path: false
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: ./
      dockerfile: docker/Dockerfile.backend
    # command: /venv/bin/python manage.py -h
    env_file:
      - path: "./.env"
        required: true
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ALLOWED_HOSTS=*
    ports:
      - "8083:8053"  # nginx
      # - "8000:8000"  # django-api

  # frontend:
  #   build:
  #     context: ./
  #     dockerfile: docker/Dockerfile.backend
  #   ports:
  #     - "9000:8080"

volumes:
  postgres-data:
